name: telematics-gis-project
author: Paul Brennan
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - geopandas
  - shapely
  - folium
  - rasterio
  - requests
  - tkinter
  - matplotlib  # sometimes needed for tkinter backends
  - pip
  - pip:
    - urllib3